DEFAULT_CENTER = 0.5
DEFAULT_PIPE_GAP = 0.3
DEFAULT_MIN_CENTER = 0
DEFAULT_MIN_PIPE_GAP = 0.2
DEFAULT_MAX_CENTER = 1
DEFAULT_MAX_PIPE_GAP = 0.9
DEFAULT_VELOCITY = 500

DEFAULT_NUM_PIPES = 5

DEFAULT_PLAYER_RADIUS = 50
DEFAULT_GRAVITY = 60
DEFAULT_JUMP_FORCE = -1000

DEFAULT_EFFECT_RADIUS = 30
DEFAULT_EFFECT_VELOCITY = 500
