DEFAULT_CENTER = 0.5
DEFAULT_PIPE_GAP = 0.3
DEFAULT_MIN_CENTER = 0
DEFAULT_MIN_PIPE_GAP = 0.2
DEFAULT_MAX_CENTER = 1
DEFAULT_MAX_PIPE_GAP = 0.7
DEFAULT_GAP = 500
DEFAULT_VELOCITY = 500
DEFAULT_MAX_NUM_PIPES = 6
DEFAULT_NUM_PIPES = 1

DEFAULT_PLAYER_RADIUS = 50
# DEFAULT_GRAVITY = 60
DEFAULT_GRAVITY = 20
# DEFAULT_JUMP_FORCE = -900
DEFAULT_JUMP_FORCE = -400
DEFAULT_NUM_MAX_PLAYERS = 10

DEFAULT_NUM_EFFECTS = 1
DEFAULT_EFFECT_MIN_RADIUS = 20
DEFAULT_EFFECT_RADIUS = 30
DEFAULT_EFFECT_MAX_RADIUS = 60
DEFAULT_EFFECT_MIN_VELOCITY = 0
DEFAULT_EFFECT_VELOCITY = 500
DEFAULT_EFFECT_MAX_VELOCITY = 1000
EFFECT_SHAPES = ["circle", "rect"]
EFFECT_COLORS = ["white", "red"]

DEFAULT_EFFECTS_THRESHOLD = 3
